# EmbedFile.cmake — generate a C header embedding a file as a byte array.
#
# Drop-in replacement for `xxd -i`. Pure CMake; no external tools.
# The generated header matches the xxd convention:
#
#   unsigned char <symbol>[] = { 0xNN, 0xNN, ... };
#   unsigned int <symbol>_len = N;
#
# so consumers that use `sizeof(<symbol>)` or the `_len` global keep
# working unchanged.
#
# Usage from a parent CMakeLists.txt:
#
#   include(EmbedFile)
#   lcl_embed_file(
#     INPUT  packages/lcl-expect/src/expect.lcl
#     OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/expect-data.h
#     SYMBOL packages_lcl_expect_src_expect_lcl
#   )
#   add_dependencies(lcl-cli generate_packages_lcl_expect_src_expect_lcl)
#
# Script-mode invocation (used internally by add_custom_command):
#
#   cmake -DEMBED_INPUT=... -DEMBED_OUTPUT=... -DEMBED_SYMBOL=... \
#         -P /path/to/EmbedFile.cmake

# --------------------------------------------------------------------------
# Script mode: do the actual file generation when invoked via `cmake -P`.
# --------------------------------------------------------------------------
if(CMAKE_SCRIPT_MODE_FILE)
    if(NOT DEFINED EMBED_INPUT OR NOT DEFINED EMBED_OUTPUT OR NOT DEFINED EMBED_SYMBOL)
        message(FATAL_ERROR
            "EmbedFile.cmake: requires -DEMBED_INPUT, -DEMBED_OUTPUT, "
            "-DEMBED_SYMBOL")
    endif()

    file(READ "${EMBED_INPUT}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _byte_count "${_hex_len} / 2")

    # Convert each hex pair "NN" → "0xNN, " in a single regex pass.
    # The trailing ", " on the last byte is stripped after.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " _bytes "${_hex}")
    string(REGEX REPLACE ", $" "" _bytes "${_bytes}")

    # Build the content with string(APPEND) — using a CMake list of
    # strings here doesn't work because list elements are separated
    # by `;`, which would eat the literal semicolons we want to write
    # at the end of the C declarations.
    set(_content "/* Generated by cmake/EmbedFile.cmake — do not edit by hand. */\n")
    string(APPEND _content "/* Source: ${EMBED_INPUT} */\n")
    string(APPEND _content "unsigned char ${EMBED_SYMBOL}[] = {\n")
    string(APPEND _content "  ${_bytes}\n")
    string(APPEND _content "};\n")
    string(APPEND _content "unsigned int ${EMBED_SYMBOL}_len = ${_byte_count};\n")
    file(WRITE "${EMBED_OUTPUT}" "${_content}")
    return()
endif()

# --------------------------------------------------------------------------
# Include mode: define the lcl_embed_file() helper.
# --------------------------------------------------------------------------
function(lcl_embed_file)
    set(_options "")
    set(_one_value INPUT OUTPUT SYMBOL TARGET)
    set(_multi_value "")
    cmake_parse_arguments(EMBED "${_options}" "${_one_value}"
                          "${_multi_value}" ${ARGN})

    if(NOT EMBED_INPUT OR NOT EMBED_OUTPUT OR NOT EMBED_SYMBOL)
        message(FATAL_ERROR
            "lcl_embed_file: INPUT, OUTPUT, and SYMBOL are all required")
    endif()

    if(NOT EMBED_TARGET)
        set(EMBED_TARGET "generate_${EMBED_SYMBOL}")
    endif()

    # Resolve INPUT to an absolute path so the custom command works
    # regardless of WORKING_DIRECTORY at invocation time.
    if(NOT IS_ABSOLUTE "${EMBED_INPUT}")
        set(EMBED_INPUT "${CMAKE_CURRENT_SOURCE_DIR}/${EMBED_INPUT}")
    endif()

    add_custom_command(
        OUTPUT "${EMBED_OUTPUT}"
        COMMAND "${CMAKE_COMMAND}"
                "-DEMBED_INPUT=${EMBED_INPUT}"
                "-DEMBED_OUTPUT=${EMBED_OUTPUT}"
                "-DEMBED_SYMBOL=${EMBED_SYMBOL}"
                -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        DEPENDS "${EMBED_INPUT}" "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        COMMENT "Embedding ${EMBED_INPUT} as ${EMBED_SYMBOL}"
        VERBATIM
    )

    add_custom_target("${EMBED_TARGET}" DEPENDS "${EMBED_OUTPUT}")
endfunction()
